---

- name: Reload systemd configs
  systemd:
    daemon_reload: yes

- name: Restart display-manager
  service:
    name: 'display-manager'
    state: 'restarted'
  when: dm__restart_on_configuration_change | bool
